### ISSUE TITLE
Should remove content of a submission annotation store if it already exists?

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-controller#39]
This is the scenario when re-running a submission...

**Comment by tschaffter** [comment]
Good question. Here are a few elements to seed the discussion

- I would tend to not remove data from past runs that failed because they may provide useful information for debugging. What is the list of data concerned? The predictions saved to the data node, the annotation added to a submission and the log files exported to synapse?
- One application I have in mind is to apply an aggregation methods that aggregate predictions available in a dataset. In order to be able to do this, I need to know which annotation stores in a dataset are associated to a successful evaluation. I could get this information by querying Synapse. Alternatively we could state that all the annotation store that are in a dataset are complete, i.e. we agree to delete annotation stores that are linked to a failed run. However, this would only be useful if I decide to aggregate all the prediction. In practice, I would probably select the predictions from a selection of submission based on their performance, which I would get from Synapse along with the information of whether the submission was successful or not. Therefore, it's OK for this application if there are annotation stores that are incomplete (typically from failed run). Moreover, I think that the system would be more robust if we accept that a dataset may include incomplete annotation store (i.e. does not include a prediction for each sample in the dataset).
- Another element of response is: Assuming that a submission is processed on more than one data hosting site, do we have a way to distinguish the "run" of a submission A on data hosting site 1 from the run of Submission A on data hosting site 2?
- Given the above points, shall we introduce a Run ID? If we create annotation stores and log files on synapse according to this Run ID, we would be able to keep data from past, failed run and we would not need to do cleaning, thus making the system more robust (cleanup is an extra operation that may fail).
- A Run ID would also be useful in ELK to distinguish from multiple run of one submission.

Alternatively, we may also consider that re-running a submission is equivalent to re-submitting a submission, which would then get a new submission ID. A case to consider is when a submission must be evaluated against multiple datasets. If at the time the user makes the submission the system supports two data hosting sites, shall we create two submissions, each with their own ID so that the user can track the progress of this two submissions in a dashboard?

If we decide to rerun a submission, is it important to keep the original submission ID? If yes, we should probably add the notion of Run IDs. Having a submission ID and Run ID (kind of a sub-submission ID) should provide more flexibility and help us conserve the information that multiple Run IDs are associated to the evaluation of one submission entity (identified by the submission ID).

Thoughts?

**Comment by thomasyu888** [comment]
Here are some initial thoughts that I had:

* I agree that we probably shouldn't remove data from past runs if unless absolutely necessary as it could help us.  The information that helps us most right now with debugging is probably the log files and the prediction files.  There are simply annotations on the submission object to tell us where those two files are stored.
* I agree that the annotation stores themselves don't necessarily need to know whether or not it belonged to a successful submission - we would query for successful submissions, then obtain their annotation store.
* I think having a run ID would be a good idea, but we would have to figure out how to store the multiple runIDs with the submission.  For instance, if submission A creates runID_A and this run fails - we restart the submission and  it succeeds with runID_B, how will we know which runID to pick?  Normally I would say we could just pick the latest runID, but if we have multiple data hosting sites, then we couldn't (unless we had {hosting_site}_{runid})
* The ELK stack would only benefit from the runid if that was the name of the container.  So the runID would be generated prior to starting the service and then subsequently used in future operations.

A bigger problem right now is that a submission isn't easily run on multiple queues unless we adopt the COVID / EHR infrastructure.  I will open another ticket to discuss...

**Comment by tschaffter** [comment]
## Update

I need to spend some time thinking about the definition of a "submission" and a "submission run".

**Comment by thomasyu888** [comment]
I added an issue here: https://github.com/Sage-Bionetworks/submission-schemas/issues/9

**Comment by tschaffter** [comment]
@thomasyu888 To the question "Should remove content of a submission annotation store if it already exists?", I think that the answer is Yes.

If we need to rerun the submission on a dataset A because the submission fails, we could have a look at the annotation first, then restart the submission. In that case, the annotation store for this submission should be emptied before attempting to save annotations generated during the new run. If the run fails again, we can look at the new state of the annotation store. Basically because we can rerun a job on a given dataset, we don't absolutely need to save the output. But we still save it for successful submission for post analysis.

If you agree with this answer, I'll close this ticket. Implementation should be tracked in a separate ticket or PR that reference this ticket.
