### ISSUE TITLE
Need access to challenge data for data node loading 

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/nlpsandbox-controller#88]
### Problem description

Do not have Read access for mcw-bot to download challenge data 

#### Steps to reproduce the issue

I was previously logged in to synapse with the mcw-box client . 

$ python scripts/push_challenge_data.py
Welcome, MCW Bot!

Traceback (most recent call last):
  File "scripts/push_challenge_data.py", line 24, in <module>
    json_ent = syn.get("syn23593068")
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/synapseclient/client.py", line 709, in get
    bundle = self._getEntityBundle(entity, version)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/synapseclient/client.py", line 1231, in _getEntityBundle
    bundle = self.restPOST(uri, body=json.dumps(requestedObjects))
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/synapseclient/client.py", line 3865, in restPOST
    response = self._rest_call('post', uri, body, endpoint, headers, retryPolicy, requests_session, **kwargs)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/synapseclient/client.py", line 3832, in _rest_call
    self._handle_synapse_http_error(response)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/synapseclient/client.py", line 3802, in _handle_synapse_http_error
    exceptions._raise_for_status(response, verbose=self.debug)
  File "/home/crdw/nlpsandbox-controller/env/lib64/python3.6/site-packages/synapseclient/core/exceptions.py", line 160, in _raise_for_status
    raise SynapseHTTPError(message, response=response)
synapseclient.core.exceptions.SynapseHTTPError: 403 Client Error:
You lack READ access to the requested entity.

#### Expected behavior

Download 12b2 2014 challenge data.

**Comment by thomasyu888** [comment]
@tschaffter ,  what are your thoughts on this?   George is trying to load the data that we use on the Sage site to load an example dataset to test the infra.  Should I provide him access?

**Comment by tschaffter** [comment]
@gkowalski @thomasyu888 Sorry for the late reply. I got slightly confused on Tuesday when George described this issue regarding what i2b2 files we were using. I mentioned to him the [JSON file](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/examples/example-patient-bundles.json) that is provided as example in the GH repos nlpsandbox/nlpsandbox-client. This file only contains the data for 5 patients. The entire i2b2 dataset is not included there because in theory we are not authorized to redistribute it.

@thomasyu888 Is the example script provided to push the data of these five patients up to date with the latest version of the client? If yes, George could use this example to test pushing data to his instance of the data node.

@thomasyu888 I was expecting to find the JSON file that we have generated for the entire i2b2 dataset in [this folder](https://www.synapse.org/#!Synapse:syn23196732) in Synapse, but it's not there. Can you please point me where it is and give George access to it?

Note that I'm planning a new release of the NLP Sandbox schemas ten days from now. This update will bring support for storing ID and contact information gold standard and predicted annotations to the data node. At this occasion we will release a new version of the i2b2 dataset in JSON format that include the gold standard for ID and contact information.

**Comment by thomasyu888** [comment]
@tschaffter, I'm hoping that with the version bump fix in the client, George's problem will go away.  The example script should work, I tested it by spinning up the datanode locally and doing:
```
pip install nlpsandbox-client
python nlpsandbox-client/examples/push_dataset.py
```

The data can be found here: https://www.synapse.org/#!Synapse:syn23593059.  Did we want to provide all the sites access to this dataset?  Will it be confusing?

**Comment by gkowalski** [comment]
Working now 

```
(venv) [crdw@darvin:~/nlpsandbox-client/examples]$ python push_dataset.py
Creating dataset: test-dataset
Creating Fhir Store: evaluation
Creating Annotation Store: goldstandard
Creating patient: 110
Creating note (110-01) for patient (110)
Creating annotation for note: 110-01
Creating note (110-02) for patient (110)
Creating annotation for note: 110-02
Creating note (110-03) for patient (110)
Creating annotation for note: 110-03
Creating note (110-04) for patient (110)
Creating annotation for note: 110-04
(venv) [crdw@darvin:~/nlpsandbox-client/examples]$
```
